"""
generate_vocab_dict.py
======================

Emit `vocab_dictionary.md` from `vocab_spec.py`. This is the canonical
source-of-truth documentation of every token our tokenizer can produce,
intended to be read by humans and future AI agents alike.

    python generate_vocab_dict.py --output stockholm_poc/vocab_dictionary.md
"""

import argparse
from pathlib import Path

import vocab_spec as VS


GRAMMAR_PREAMBLE = """\
# Spatial Foundation Model — Vocabulary Dictionary

> Auto-generated from `vocab_spec.py`. Do not edit this file by hand;
> update the spec and re-run `python generate_vocab_dict.py`.

## Sequence grammar

A training corpus is one flat token stream laid out like this:

```
corpus         := <CONTEXT_START> <REGION_*> <CLIMATE_*> <DENSITY_*> <CONTEXT_END>
                  object+

object         := <KIND_START> <TAG_KEY_VALUE> extra_attr* <X_#> <Y_#> geometry? <KIND_END>

extra_attr     := <SURFACE_*> | <LIT_*> | <LANES_*> | <ACCESS_*>
                  | <ONEWAY_*> | <BRIDGE_YES> | <TUNNEL_YES>
                  | <SPEED_*> | <LEVELS_*> | <HEIGHT_*>

geometry       := (<dx_N> <dy_M>)+                              (linear feature)
                  | (<dx_N> <dy_M>)+ (<PART_SEP> <X_#> <Y_#> (<dx_N> <dy_M>)+)*   (multipolygon)
                  | (empty)                                     (POI)
```

- `KIND`  ∈ `CONTEXT`, `BUILDING`, `ROAD`, `POI`, `LANDUSE`, `WATERWAY`,
           `RAILWAY`, `NATURAL_LINE`
- `<X_#>` / `<Y_#>` place the object inside a **chunk-local 256×256 grid**.
- `<dx_#>` / `<dy_#>` are **1-meter relative jumps** in the range
  `[-32, +32]`. Longer edges are expressed as multiple (dx, dy) token
  pairs. Vertex N's position is `vertex[N-1] + (dx, dy)` in meters.
- Tags carry the OSM key: `<TAG_AMENITY_HOSPITAL>`, `<TAG_SHOP_SUPERMARKET>`,
  `<TAG_BUILDING_HOUSE>`, etc. Unknown values collapse to
  `<TAG_<KEY>_OTHER>`.
- The three fields `name=*`, `operator=*`, and any other high-cardinality
  identifier tags are **intentionally excluded**.

"""


def _section(title: str, tokens) -> str:
    lines = [f"## {title}", ""]
    lines.append(f"- Count: **{len(tokens)}**")
    lines.append("")
    lines.append("```")
    for t in tokens:
        lines.append(t)
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def _tag_section() -> str:
    lines = [
        "## Semantic Tags (TAG_KEY_VALUE)",
        "",
        "Every accepted (key, value) pair gets its own token. Values not",
        "in the allow-list collapse to `<TAG_<KEY>_OTHER>`. The model sees",
        "`<TAG_AMENITY_HOSPITAL>` and `<TAG_AMENITY_OTHER>` as distinct,",
        "first-class primitives.",
        "",
    ]
    total = 0
    for key, values in VS.TAG_ALLOWED_VALUES.items():
        lines.append(f"### `{key}` ({len(values) + 1} tokens incl. OTHER)")
        lines.append("")
        lines.append("```")
        for v in values:
            lines.append(f"<TAG_{key.upper()}_{VS._sanitize(v)}>")
        lines.append(f"<TAG_{key.upper()}_OTHER>")
        lines.append("```")
        lines.append("")
        total += len(values) + 1
    lines.append(f"**Total TAG tokens: {total}**")
    lines.append("")
    return "\n".join(lines)


def build_document() -> str:
    parts = [GRAMMAR_PREAMBLE]

    parts.append("## 1. Geometry Tokens (dx / dy)\n")
    parts.append(
        "1-meter relative jumps, range `[-32, +32]`. One token per axis."
        f" Total: {2 * (2 * VS.DELTA_RANGE + 1)} ({2 * VS.DELTA_RANGE + 1} dx + {2 * VS.DELTA_RANGE + 1} dy).\n"
    )
    parts.append("```")
    for v in range(-VS.DELTA_RANGE, VS.DELTA_RANGE + 1):
        parts.append(f"<dx_{v}>")
    parts.append("```")
    parts.append("```")
    for v in range(-VS.DELTA_RANGE, VS.DELTA_RANGE + 1):
        parts.append(f"<dy_{v}>")
    parts.append("```\n")

    parts.append("## 2. Anchor Tokens (X / Y)\n")
    parts.append(
        f"Chunk-local {VS.GRID_SIZE}×{VS.GRID_SIZE} grid position. "
        "Only the lowest/highest are shown for brevity.\n"
    )
    parts.append("```")
    parts.append(f"<X_0> ... <X_{VS.GRID_SIZE - 1}>")
    parts.append(f"<Y_0> ... <Y_{VS.GRID_SIZE - 1}>")
    parts.append(f"# Total: {2 * VS.GRID_SIZE} tokens")
    parts.append("```\n")

    parts.append(_tag_section())

    parts.append("## 4. Attribute Tokens\n")
    parts.append(_section("Surface (`highway=*`)",
                          [f"<SURFACE_{v.upper()}>" for v in VS.SURFACE_VALUES]))
    parts.append(_section("Lit (`highway=*`)",
                          [f"<LIT_{v.upper()}>" for v in VS.LIT_VALUES]))
    parts.append(_section("Lanes (`highway=*`)",
                          [f"<LANES_{v}>" for v in VS.LANES_VALUES]))
    parts.append(_section("Access (`highway=*`)",
                          [f"<ACCESS_{v.upper()}>" for v in VS.ACCESS_VALUES]))
    parts.append(_section("Oneway (`highway=*`)",
                          [f"<ONEWAY_{v.upper()}>" for v in VS.ONEWAY_VALUES]))
    parts.append(_section("Bridge / Tunnel (binary, emitted only when truthy)",
                          ["<BRIDGE_YES>", "<TUNNEL_YES>"]))
    parts.append(_section("Road Speed (bucketed `maxspeed=*`)",
                          [f"<SPEED_{v.upper()}>" for v in VS.SPEED_VALUES]))
    parts.append(_section("Building Levels (bucketed `building:levels=*`)",
                          [f"<LEVELS_{v.upper()}>" for v in VS.LEVELS_VALUES]))
    parts.append(_section("Building Height (bucketed `height=*`)",
                          [f"<HEIGHT_{v.upper()}>" for v in VS.HEIGHT_VALUES]))

    parts.append("## 5. Structural Tokens\n")
    parts.append(_section("Kinds (start / end pairs)",
                          [t for kind in VS.KINDS for t in (f"<{kind}_START>", f"<{kind}_END>")]))
    parts.append(_section("Separators", ["<PART_SEP>"]))

    parts.append("## 6. Macro Context\n")
    parts.append(_section("Regions", [f"<REGION_{r}>" for r in VS.REGIONS]))
    parts.append(_section("Climates", [f"<CLIMATE_{c}>" for c in VS.CLIMATES]))
    parts.append(_section("Densities", [f"<DENSITY_{d}>" for d in VS.DENSITIES]))

    total = VS.vocabulary_size()
    parts.append("## Summary\n")
    parts.append(f"- **Total unique tokens defined in spec: {total}**")
    parts.append(f"- Target ceiling: 4,096 tokens")
    parts.append(f"- Headroom: {4096 - total} tokens\n")

    return "\n".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", "-o", default="vocab_dictionary.md")
    args = parser.parse_args()

    doc = build_document()
    Path(args.output).write_text(doc, encoding="utf-8")
    total = VS.vocabulary_size()
    print(f"wrote {args.output}")
    print(f"total vocab size: {total} (ceiling 4096)")


if __name__ == "__main__":
    main()
